export const actionType = {
    'ADD_PRODUCT': 'ADD_PRODUCT',
    'FETCH_PRODUCT': 'FETCH_PRODUCT',
    'EDIT_PRODUCT': 'EDIT_PRODUCT',
    'TOGGLE_SIGN_IN': 'TOGGLE_SIGN_IN',
    'SET_ROLE': 'SET_ROLE',
}